---
engines:
  brakeman:
    enabled: true
    exclude_fingerprints:
    - 2f63d663e9f35ba60ef81d56ffc4fbf0660fbc2067e728836176bc18f610f77f
  bundler-audit:
    enabled: false
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.rhtml"
  - "**.slim"
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
exclude_paths:
- config/
- db/
- features/
- script/
- spec/
- vendor/
- "*/**/*.min.js"
- "*/**/jquery.js"
- "*/**/prototype.js"
- "*/**/controls.js"
- "*/**/effects.js"
- "*/**/dragdrop.js"
- "*/**/builder.js"
- "*/**/slider.js"
- "app/controllers/bulk_downloads_controller.rb"
- "app/controllers/checkins_controller.rb"
- "app/controllers/donations_controller.rb"
- "app/controllers/imports_controller.rb"
- "app/controllers/info_controller.rb"
- "app/controllers/labels_controller.rb"
- "app/controllers/reports_controller.rb"
- "app/controllers/showdates_controller.rb"
- "app/controllers/shows_controller.rb"
- "app/controllers/txns_controller.rb"
- "app/controllers/valid_vouchers_controller.rb"
- "app/controllers/vouchertypes_controller.rb"
- "app/helpers/*"
- "app/models/auto_importer.rb"
- "app/models/auto_importers/goldstar_auto_importer.rb"
- "app/models/bulk_download.rb"
- "app/models/bulk_downloads/brown_paper_tickets_download.rb"
- "app/models/bulk_downloads/tba_download.rb"
- "app/models/email_list.rb"
- "app/models/external_ticket_orders.rb"
- "app/models/import.rb"
- "app/models/imports/ticket_sales_import.rb"
- "app/models/imports/ticket_sales_imports/*"
- "app/models/report.rb"
- "app/models/reports/*"
- "app/models/ticket_offer.rb"
- "app/models/transaction_details_report.rb"
- "app/models/vouchertype.rb"
- "lib/*"
- "public/javascripts/*"
